//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assign3_AIAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PieChartValue1
    {
        public decimal Value { get; set; }
        public string Name { get; set; }
    }
}
