//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIAD_Assign7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTable
    {
        public int TicketId { get; set; }
        public string Username { get; set; }
        public string ProbDesc { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string AdditionalComments { get; set; }
        public string Resolution { get; set; }
        public Nullable<System.DateTime> DateResolved { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    }
}
