SET IDENTITY_INSERT [dbo].[Sports] ON
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (1, N'Team A', N'Joe', 14000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (2, N'Team A', N'Jane', 4000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (3, N'Team A', N'Jill', 6000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (4, N'Team A', N'Jack', 7000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (5, N'Team A', N'Jacob', 3000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (6, N'Team B', N'Bala', 10000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (7, N'Team B', N'Sameera', 8000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (8, N'Team B', N'Sanath', 1000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (9, N'Team B', N'Narendra', 500, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (10, N'Team B', N'Suchitra', 1500, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (11, N'Team C', N'Swetha', 8000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (12, N'Team C', N'Sowmya', 9000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (13, N'Team C', N'Lalitha', 6500, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (14, N'Team C', N'Nimisha', 12000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (15, N'Team C', N'Swaroop', 7000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (16, N'Team D', N'Sameer', 9000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (17, N'Team D', N'Harshika', 400, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (18, N'Team D', N'Vihari', 6500, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (19, N'Team D', N'Kalyan', 17000, 12000, NULL)
INSERT INTO [dbo].[Sports] ([Id], [Team], [Name], [YTDSales], [Goal], [Password]) VALUES (20, N'Team D', N'Karthik', 2000, 12000, NULL)
SET IDENTITY_INSERT [dbo].[Sports] OFF
